flags: {}
extra-package-dbs: []
extra-deps: 
    - yesod-markdown-0.11.1

packages:
- Carnap/
- Carnap-Server/
- Carnap-Client/
#resolver: lts-6.25
resolver: lts-6.30

#Needed in order to use stack with nix in development
nix:
  enable: true
  packages: [glpk, pcre, zlib, postgresql]
